// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLIsowdYAIVWRAu0L9R0f-M0YWmdsE_k',
    appId: '1:567185470892:web:f488720bb749da6eb3f609',
    messagingSenderId: '567185470892',
    projectId: 'food-app-56cca',
    authDomain: 'food-app-56cca.firebaseapp.com',
    storageBucket: 'food-app-56cca.appspot.com',
    measurementId: 'G-2JY12WLFS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3_siEaxMLV5Q77Wfrfrkd3lrB5ALeG8',
    appId: '1:567185470892:android:8a970de5031b6e3ab3f609',
    messagingSenderId: '567185470892',
    projectId: 'food-app-56cca',
    storageBucket: 'food-app-56cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVGVoBDw9GqrGr3cLLirO3Iw9rx1z6QI',
    appId: '1:567185470892:ios:8a8dda57b9a96052b3f609',
    messagingSenderId: '567185470892',
    projectId: 'food-app-56cca',
    storageBucket: 'food-app-56cca.appspot.com',
    iosClientId: '567185470892-ga9sjf0kb4m5r2f6eij0v0tlkj3vceog.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyVGVoBDw9GqrGr3cLLirO3Iw9rx1z6QI',
    appId: '1:567185470892:ios:004664b29507b41ab3f609',
    messagingSenderId: '567185470892',
    projectId: 'food-app-56cca',
    storageBucket: 'food-app-56cca.appspot.com',
    iosClientId: '567185470892-m45c7lpm4oohbmt3oij70i5q7cvpoljd.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
